ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255),
    ADD COLUMN IF NOT EXISTS address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(64);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users (email);
